CREATE TABLE currently_reading (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  media_name TEXT NOT NULL,
  author TEXT,
  media_url TEXT, 
  current_progress INTEGER DEFAULT 0 NOT NULL,
  notes TEXT,
  finished BOOLEAN DEFAULT false,
  media_type TEXT NOT NULL,
  date_started DATE DEFAULT now() NOT NULL,
  date_finished DATE
)