DROP TABLE IF EXISTS currently_reading;
DROP TABLE IF EXISTS profiles;

CREATE TABLE profiles (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  firstname text not null,
  lastname text not null,
  email text not null,
  user_login TEXT not null,
  user_password TEXT not null,
  weekly_hours INTEGER,
  progress INTEGER,
  days_left INTEGER
);

CREATE TABLE currently_reading (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  media_name TEXT NOT NULL,
  author TEXT,
  media_url TEXT, 
  current_progress INTEGER DEFAULT 0 NOT NULL,
  notes TEXT,
  finished BOOLEAN NOT NULL,
  media_type TEXT NOT NULL,
  date_started DATE DEFAULT now() NOT NULL,
  date_finished DATE,
  library_owner INTEGER REFERENCES profiles(id)
);